In [2]:
import pandas as pd

In [21]:
file = '1.txt'
car = pd.read_csv(file)
car = car.sort_values('#id',ascending=True)
car

          #id  from    to  speed planTime)
36914   10000   894  1019      6        2)
22830   10002   554  1180      8       17)
645     10003   998   552     10       18)
12043   10005  1567   493      6        2)
33718   10006  1019   581      4       24)
59701   10008  1608  1855     16       29)
1813    10011   123  1238     10        4)
37624   10012  1934  1019     14       14)
43551   10013   211  1085      8        7)
29168   10014   541  1834      6        4)
40944   10015   863  1697     14       21)
25590   10019  1531   667      4       24)
49567   10023   297  1432     14       10)
20045   10025  1228  1896      8       29)
36106   10029   977   902      6        2)
52746   10030   661   834     12        6)
60789   10034   123  1671     12       11)
45381   10035   635  1834      6        5)
42060   10036  1580   834     10       17)
11389   10037  1197   138     16        7)
29408   10038   834  1197     16       25)
34434   10039   554   863     12       16)
43778   10040   902  1563     12       27)
50895   10041  1834   913     10       16)
39776   10042  1192  1503     10       13)
45195   10043  1613  1019     12        9)
20064   10044   324  1671     14       14)
8818    10045  1152  1432      8       15)
47931   10046   863   745     14       26)
3089    10047   537  1019     10       25)
...       ...   ...   ...    ...       ...
39848  109951   829  1503     12        3)
55779  109955  1503   964      4        2)
46272  109957  1855  1390     10       23)
57150  109959    51   493      4       25)
31424  109960  1739  1896      8       11)
8935   109961  1508  1896      6       15)
32024  109964  1197  1465     12       14)
47269  109965   129  1855     16       21)
28732  109967   617  1855      6       17)
37569  109968  1152  1940      4       19)
42967  109969   870  1613      8       10)
43120  109973  1697  1180     14       11)
40865  109974  1217  1982     10       14)
18168  109975  1019  1058      4       12)
47254  109977  1655   313      4        1)
11953  109978   201  1590      4        9)
17158  109980   980  1724     10       12)
11548  109982  1423  1809     12       23)
11619  109983   745   138      6       17)
10152  109985  1087  1238     16        2)
439    109987   687   129      6       11)
10477  109988   313   998     16       22)
54470  109989  1305  1855     16       11)
1479   109990   795   426     10       13)
26178  109991   581   913      4       19)
39     109994  1834   902     10       29)
34946  109995  1180   745      6       25)
31919  109997  1305   834     10        3)
9227   109998  1217  1623     16       21)
32938  109999  1624  1305     10       10)

[61440 rows x 5 columns]

In [14]:
car['planTime)'].value_counts()

TypeError: 'NoneType' object is not subscriptable

In [30]:
car['speed'].value_counts()

6    2584
8    2566
4    2548
2    2542
Name: speed, dtype: int64

In [31]:
pd.set_option('display.max_row',100)
car['from'].value_counts()

53    195
64    186
7     184
17    183
21    182
61    177
36    175
51    175
60    174
56    173
3     173
52    173
43    171
16    171
44    169
29    167
62    166
13    166
59    165
49    163
63    163
8     163
22    163
48    161
35    160
24    160
34    160
50    160
38    160
6     159
1     159
41    159
18    159
58    158
9     157
42    157
20    157
14    157
2     156
30    156
27    156
37    155
11    155
26    154
45    153
57    153
39    152
23    152
32    151
55    151
12    150
5     150
25    150
15    149
4     149
47    149
10    148
46    147
40    147
54    145
19    141
28    141
33    136
31    134
Name: from, dtype: int64

In [35]:
gp=car.groupby(by=['speed','planTime)'])
gp.size()

speed  planTime)
2       1)          219
        10)         257
        2)          244
        3)          267
        4)          266
        5)          285
        6)          259
        7)          247
        8)          237
        9)          261
4       1)          304
        10)         251
        2)          229
        3)          238
        4)          276
        5)          246
        6)          248
        7)          267
        8)          260
        9)          229
6       1)          281
        10)         245
        2)          268
        3)          243
        4)          239
        5)          270
        6)          236
        7)          254
        8)          267
        9)          281
8       1)          247
        10)         254
        2)          266
        3)          234
        4)          266
        5)          263
        6)          269
        7)          281
        8)          262
        9)          224
dtype: int64